### ISSUE TITLE
ERROR: Directory 'pieutils/' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.

### ISSUE THREAD

**Issue by rafiktelli** [wbsg-uni-mannheim/ExtractGPT#1]
Hello, 
I am trying to run the command : pip install /pieutils and I am getting this error. This may be caused because of the absence of a file pyproject.toml or setup.py. 
Thanks in advance.

**Comment by abrinkmann** [comment]
Hello @rafiktelli ,

Thanks for pointing us to this issue.
The correct command to install pieutils is to run: `pip install .`
The README file is adjusted accordingly.

Please let us know if you have any further problems running the code.

**Comment by rafiktelli** [comment]
Hello @abrinkmann, 
Thank you for your response. 
I am having another issue regarding the use of Azure OpenAI instead of a simple account of OpenAI. Do you have an idea about how to change the connection in this case? And can you tell me what openai plan you have used in this project. 
Thank you in advance.

**Comment by abrinkmann** [comment]
Hello @rafiktelli ,

Each python script contains an initialisation of the used LLM for example [here](https://github.com/wbsg-uni-mannheim/ExtractGPT/blob/922fdaebccb985f91b96ae3495969fdd57af0b29/prompts/5_in-context_learning/in_context_schema_description_with_example_values_ensemble_shuffle.py#L81).
If you use Azure OpenAI, you have to initialize an Azure OpenAI model instead of an OpenAI model or an open-source model from the Huggingface hub.

We created a paid account on the OpenAI platform. Does this answer your question regarding the OpenAI plan?

**Comment by rafiktelli** [comment]
Yes it does. 
Thank you so much for your answers. 
I will try to change the script as you mentioned. I appreciate your help.
